clc;
close all;
clear all;
t=0:0.01:1;
fs=0:1:100;
f1=input('enter the frequency');
f2=input('enter the frequency');
t1=2*pi*f1*t;
t2=2*pi*f2*t;
x1=5*sin(t1);
x2=2*sin(t2);
x3=x1-x2;
subplot(2,2,1);
plot(t,x1);
xlabel('time');
ylabel('amp');
title('sine wave');
subplot(2,2,2);
plot(t,x2);
xlabel('time');
ylabel('amp');
title('cos wave');
subplot(2,2,3);
plot(t,x3);
xlabel('time');
ylabel('amp');
title('add of two waves');
y=fft(x3);
subplot(2,2,4);
plot(fs,abs(y));
xlabel('freq');
ylabel('mag');
title('spectrum waves');
