clc;
close all;
clear all;
%fs=input('enter sampling freq');
t=0:0.001:1;
am=input('enter the message sgl amp');
ac=input('enter the carrier sgl amp');
fm=input('enter the message sgl fre');
fc=input('enter the carrier sgl fre');
m=am*cos(2*pi*fm*t);
c=fm*cos(2*pi*fc*t);
d=m.*c;
a=c.*(1+m);
subplot(2,2,1);
plot(t,c);
xlabel('time');
ylabel('ampli');
title('carrier signal');
subplot(2,2,2);
plot(t,m);
xlabel('time');
ylabel('ampli');
title('message signal');
subplot(2,2,3);
plot(t,a);
xlabel('time');
ylabel('ampli');
title('dsb-sc');
fs=0:1:1000;
D=fft(a);
subplot(2,2,4);
plot(fs,abs(D));
xlabel('frequency');
ylabel('mag');
title('fft of dsb-sc');

