clc;
close all;
clear all;
t=0:0.01:1;
f=input('enter the frequency');
t1=2*pi*f*t;
x1=sin(t1);
x2=cos(t1);
x3=x1-x2;
subplot(2,2,1);
plot(t,x1);
xlabel('time');
ylabel('amp');
title('sine wave');
subplot(2,2,2);
plot(t,x2);
xlabel('time');
ylabel('amp');
title('cos wave');
subplot(2,2,3);
plot(t,x3);
xlabel('time');
ylabel('amp');
title('sub of two waves');