clc;
close all;
clear all;
t=0:1:8;
x=[0 0 1 2 3 4 5 0 0];
subplot(2,2,1);
stem(t,x);
xlabel('time');
ylabel('ampli');
title('original sgl');
subplot(2,2,2);
stem(t/2,x);
xlabel('time');
ylabel('ampli');
title('compression');
subplot(2,2,3);
stem(t/0.5,x);
xlabel('time');
ylabel('ampli');
title('expansion');